/** Local save file — gitignored. Auto-generated by maple-bot. */
export default {
  "version": 1,
  "savedAt": "2026-08-18T04:03:02.300Z",
  "items": [
    {
      "id": "3261ea2e-2372-467b-a99f-30be483918c8",
      "name": "assassins",
      "moves": [
        {
          "id": "90bc9483-5656-4bd4-ad8f-ce4ce1096e67",
          "name": "Jump",
          "buttonKey": "alt",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "29460dcf-971a-4989-9688-4b3138997cd8",
          "name": "Dash",
          "buttonKey": "r",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "7ead6d84-1bf3-481f-9300-8874b2e1ed60",
          "name": "Flash Jump",
          "buttonKey": "d",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "9e95e41b-d3e4-4d73-be1f-35c2c8a8a32f",
          "name": "Throwing Stars",
          "buttonKey": "a",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "3e67dc0d-97cd-42dd-8328-0187b10f479d",
          "name": "Multi-Star Throw",
          "buttonKey": "shift",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "6362d64a-3247-4584-9482-56f9a444a4a9",
          "name": "Large Shuriken",
          "buttonKey": "space",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "1117796a-197f-466e-8fd3-7764678531fc",
          "name": "Ghost Summon",
          "buttonKey": "g",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "662aa791-80e0-4fd7-828a-a2401de216d8",
          "name": "Pick Up",
          "buttonKey": "x",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "24e47ed5-42d8-4c11-a970-250307552e77",
          "name": "Sit",
          "buttonKey": "n",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "2ad8fd3d-fe3a-4fe9-b315-62b534e92e36",
          "name": "Speed Run",
          "buttonKey": "z",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "55ca1127-707e-4b5f-9937-555778f07624",
          "name": "Stand",
          "buttonKey": "v",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "4cce0825-5d94-45c5-9319-64bc4848f94b",
          "name": "To The Map",
          "buttonKey": "1",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "a7f01055-e0ff-4028-8ff6-fbecf31f5101",
          "name": "To The Channel",
          "buttonKey": "2",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "2ad285c9-f2a9-4a36-9292-9128c478d51f",
          "name": "To The Party",
          "buttonKey": "4",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "7cdd307b-d8c9-4837-a298-94b33b281718",
          "name": "Move Menu",
          "buttonKey": "tab",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "e93673bb-8510-4ba6-b1ab-3394bf2a1572",
          "name": "Quest",
          "buttonKey": "q",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "143c294e-d78d-45a2-9c0f-2b78a1f4a3f0",
          "name": "World Map",
          "buttonKey": "w",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "0755ace4-69fe-49e4-a9b6-6ad74454033a",
          "name": "Equipment",
          "buttonKey": "e",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "4ed98e4c-d9cc-4a10-a465-a99e302a6275",
          "name": "User List",
          "buttonKey": "u",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "af77afa6-feae-4ffb-990e-f3fa46404e3f",
          "name": "Item",
          "buttonKey": "i",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "bd26cfeb-bfbb-4ef5-abb1-17b9472cf1dd",
          "name": "Party",
          "buttonKey": "p",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "da838462-0975-4f51-8e1e-4a6c57e92706",
          "name": "Set Key",
          "buttonKey": "\\",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "ac255436-711c-4b5d-8eed-ae239e36232b",
          "name": "Ability",
          "buttonKey": "f",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "319156ab-5cd6-49fd-86f6-ac7befaebe37",
          "name": "Whisper",
          "buttonKey": "h",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "2ab016d7-5f7e-4517-be3c-fd224b0d92a1",
          "name": "Skill",
          "buttonKey": "k",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "31b20d4d-0cc1-4b47-b35d-099afeea00cf",
          "name": "Helper",
          "buttonKey": "l",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "2fc886e3-f87f-4998-adb4-a7f6d0d1bc65",
          "name": "Chat+",
          "buttonKey": ";",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "c43ef612-d343-41f3-8994-03a1c623fbbd",
          "name": "NPC Chat",
          "buttonKey": "b",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "ce0a3b04-8b85-4266-8cd4-b787aae9ae28",
          "name": "Mini Map",
          "buttonKey": "m",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        }
      ],
      "buffs": [
        {
          "id": "2a8d8428-4ad0-4be6-b0c6-9784e556cfbf",
          "name": "buff 1",
          "buttonKey": "a",
          "cooldownSeconds": 500,
          "castTimeSeconds": 1
        },
        {
          "id": "c44a9bec-259b-46a1-b56c-1debcdf4df47",
          "name": "buff 2",
          "buttonKey": "s",
          "cooldownSeconds": 500,
          "castTimeSeconds": 1
        },
        {
          "id": "f78b4424-0d26-4fb2-ba31-aefcc0b46ffc",
          "name": "buff 3",
          "buttonKey": "d",
          "cooldownSeconds": 497.3,
          "castTimeSeconds": 1
        },
        {
          "id": "a7ae4bef-628d-4660-9bde-5623b093e353",
          "name": "buff 4",
          "buttonKey": "c",
          "cooldownSeconds": 500,
          "castTimeSeconds": 1
        }
      ],
      "attacks": [
        {
          "id": "40e1ba25-2c49-4042-8fef-d27b2309e5d5",
          "name": "lucky sev",
          "buttonKey": "shift",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        },
        {
          "id": "16818c82-fa75-4b53-841b-8db2494ecc7d",
          "name": "drain",
          "buttonKey": "space",
          "cooldownSeconds": 0.3,
          "castTimeSeconds": 0.3
        }
      ]
    }
  ]
} as const;
