import fs from 'node:fs/promises'
import path from 'node:path'
import { dialog } from 'electron'
import {
  BOT_SETTINGS_SAVE_FILE,
  BOT_SETTINGS_SAVE_VERSION,
  type BotSettingsSaveFile,
} from '../src/types/botSettingsSave'
import {
  DEFAULT_BOT_SETTINGS,
  normalizeBotSettings,
  type BotSettings,
} from '../src/types/botSettings'

export const LIE_DETECTOR_TEMPLATE_FILE = '.lie-detector-template'

const SAVE_FILE_HEADER =
  '/** Local save file — gitignored. Auto-generated by maple-bot. */\nexport default '

function getSavePath(appRoot: string): string {
  return path.join(appRoot, BOT_SETTINGS_SAVE_FILE)
}

function getTemplatePath(appRoot: string): string {
  return path.join(appRoot, LIE_DETECTOR_TEMPLATE_FILE)
}

function parseSaveFileContent(content: string): BotSettingsSaveFile | null {
  const match = content.match(/export default\s+([\s\S]+?)\s+as const;?\s*$/m)
  if (!match) return null

  try {
    return JSON.parse(match[1]) as BotSettingsSaveFile
  } catch {
    return null
  }
}

export function createBotSettingsHandlers(appRoot: string) {
  const savePath = getSavePath(appRoot)
  const templatePath = getTemplatePath(appRoot)

  return {
    async loadSettings(): Promise<BotSettings> {
      try {
        const content = await fs.readFile(savePath, 'utf8')
        const parsed = parseSaveFileContent(content)
        if (!parsed || parsed.version !== BOT_SETTINGS_SAVE_VERSION) {
          return { ...DEFAULT_BOT_SETTINGS }
        }
        return normalizeBotSettings(parsed.settings)
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
          return { ...DEFAULT_BOT_SETTINGS }
        }
        throw error
      }
    },

    async saveSettings(settings: BotSettings): Promise<{ savedAt: string }> {
      const payload: BotSettingsSaveFile = {
        version: BOT_SETTINGS_SAVE_VERSION,
        savedAt: new Date().toISOString(),
        settings: normalizeBotSettings(settings),
      }

      const content = `${SAVE_FILE_HEADER}${JSON.stringify(payload, null, 2)} as const;\n`
      await fs.writeFile(savePath, content, 'utf8')
      return { savedAt: payload.savedAt }
    },

    async getTemplateInfo(): Promise<{
      hasTemplate: boolean
      width: number | null
      height: number | null
    }> {
      try {
        await fs.access(templatePath)
        const data = await fs.readFile(templatePath)
        const dimensions = readPngDimensions(data)
        return {
          hasTemplate: true,
          width: dimensions?.width ?? null,
          height: dimensions?.height ?? null,
        }
      } catch {
        return {
          hasTemplate: false,
          width: null,
          height: null,
        }
      }
    },

    async getTemplateDataUrl(): Promise<string | null> {
      try {
        const data = await fs.readFile(templatePath)
        const mime = guessImageMime(data)
        return `data:${mime};base64,${data.toString('base64')}`
      } catch {
        return null
      }
    },

    async pickTemplateImage(): Promise<{
      ok: boolean
      width: number | null
      height: number | null
      message?: string
    }> {
      const result = await dialog.showOpenDialog({
        title: 'Choose lie detector template image',
        properties: ['openFile'],
        filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'webp'] }],
      })

      if (result.canceled || result.filePaths.length === 0) {
        return { ok: false, width: null, height: null, message: 'No file selected' }
      }

      const sourcePath = result.filePaths[0]
      const data = await fs.readFile(sourcePath)
      await fs.writeFile(templatePath, data)
      const dimensions = readPngDimensions(data)

      return {
        ok: true,
        width: dimensions?.width ?? null,
        height: dimensions?.height ?? null,
      }
    },
  }
}

function guessImageMime(data: Buffer): string {
  if (data.length >= 3 && data[0] === 0xff && data[1] === 0xd8 && data[2] === 0xff) {
    return 'image/jpeg'
  }
  if (
    data.length >= 12 &&
    data.toString('ascii', 0, 4) === 'RIFF' &&
    data.toString('ascii', 8, 12) === 'WEBP'
  ) {
    return 'image/webp'
  }
  return 'image/png'
}

function readPngDimensions(
  data: Buffer,
): { width: number; height: number } | null {
  if (data.length < 24) return null
  if (data.toString('ascii', 1, 4) !== 'PNG') return null

  return {
    width: data.readUInt32BE(16),
    height: data.readUInt32BE(20),
  }
}
