import fs from 'node:fs/promises'
import path from 'node:path'
import {
  HOTKEY_SAVE_FILE,
  MINIMAP_SAVE_FILE,
  REGISTRY_SAVE_VERSION,
  ROUTINE_SAVE_FILE,
  type HotkeySaveFile,
  type MinimapSaveFile,
  type RegistrySaveFile,
  type RoutineSaveFile,
} from '../src/types/registrySave'

const SAVE_FILE_HEADER =
  '/** Local save file — gitignored. Auto-generated by maple-bot. */\nexport default '

function getSavePath(appRoot: string, fileName: string): string {
  return path.join(appRoot, fileName)
}

function parseSaveFileContent<T>(content: string): RegistrySaveFile<T> | null {
  const match = content.match(/export default\s+([\s\S]+?)\s+as const;?\s*$/m)
  if (!match) return null

  try {
    return JSON.parse(match[1]) as RegistrySaveFile<T>
  } catch {
    return null
  }
}

async function readSaveFile<T>(
  filePath: string,
): Promise<RegistrySaveFile<T>['items']> {
  try {
    const content = await fs.readFile(filePath, 'utf8')
    const parsed = parseSaveFileContent<T>(content)
    if (!parsed || parsed.version !== REGISTRY_SAVE_VERSION) return []
    return parsed.items
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []
    throw error
  }
}

async function writeSaveFile<T extends { id: string; name: string }>(
  filePath: string,
  items: T[],
): Promise<RegistrySaveFile<T>> {
  const payload: RegistrySaveFile<T> = {
    version: REGISTRY_SAVE_VERSION,
    savedAt: new Date().toISOString(),
    items,
  }

  const content = `${SAVE_FILE_HEADER}${JSON.stringify(payload, null, 2)} as const;\n`
  await fs.writeFile(filePath, content, 'utf8')
  return payload
}

export function createRegistrySaveHandlers(appRoot: string) {
  const routinePath = getSavePath(appRoot, ROUTINE_SAVE_FILE)
  const hotkeyPath = getSavePath(appRoot, HOTKEY_SAVE_FILE)
  const minimapPath = getSavePath(appRoot, MINIMAP_SAVE_FILE)

  return {
    loadRoutines: () => readSaveFile<RoutineSaveFile['items'][number]>(routinePath),
    saveRoutines: (items: RoutineSaveFile['items']) =>
      writeSaveFile(routinePath, items),
    loadHotkeys: () => readSaveFile<HotkeySaveFile['items'][number]>(hotkeyPath),
    saveHotkeys: (items: HotkeySaveFile['items']) =>
      writeSaveFile(hotkeyPath, items),
    loadMinimaps: () => readSaveFile<MinimapSaveFile['items'][number]>(minimapPath),
    saveMinimaps: (items: MinimapSaveFile['items']) =>
      writeSaveFile(minimapPath, items),
    getSaveFilePaths: () => ({
      routines: routinePath,
      hotkeys: hotkeyPath,
      minimaps: minimapPath,
    }),
  }
}
